version: '3.8'

services:
  php:
    image: php:8.2-cli
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - COMPOSER_CACHE_DIR=/app/.composer-cache
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: otp_test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
  redis_data:
